apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-wizard
  namespace: node-wizard
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
      - delete
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-wizard-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: node-wizard
  namespace: node-wizard
roleRef:
  kind: ClusterRole
  name: node-wizard-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: node-wizard
  namespace: node-wizard