apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-wizard
  namespace: node-wizard
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: node-wizard
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node-wizard
    spec:
      imagePullSecrets:
        - name: ghcr-sec
      serviceAccountName: node-wizard
      containers:
      - image: ghcr.io/pehlicd/node-wizard:dev-latest
        imagePullPolicy: Always
        name: node-wizard
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30