name: node-wizard
serviceAccountName: node-wizard
replicaCount: 3
image:
  repository: ghcr.io/pehlicd/node-wizard
  tag: dev-latest
  pullPolicy: Always
resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi