apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: nodewizard
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nodewizard
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nodewizard
    spec:
      imagePullSecrets:
        - name: ghcr-sec
      serviceAccountName: {{ .Values.serviceAccountName  }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: nodewizard
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: LOG_LEVEL
          value: {{ .Values.env.logLevel }}
        - name: IGNORE_ALL_DAEMONSETS
          value: {{ .Values.env.ignoreAllDaemonsets }}
        - name: DELETE_EMPTY_DIR_DATA
          value: {{ .Values.env.deleteEmptyDirData }}
        - name: FORCE_DELETE_PODS
          value: {{ .Values.env.forceDeletePods }}
        resources:
        {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30